site_name: Goracle
site_description: 'Открытая база знаний по внутреннему устройству Go — от планировщика до архитектурных паттернов'
site_author: '@venexene'
repo_url: https://github.com/venexene/goracle
edit_uri: edit/main/
site_dir: site

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Тёмная тема
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Светлая тема
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search:
      lang: ru

nav:
  - Главная: index.md
  - Computer Science:
      - Обзор: computer-science/index.md
      - Алгоритмы и структуры данных: computer-science/Алгоритмы и структуры данных/algorithms-and-data-structures.md
      - Параллельность и конкурентность: computer-science/Параллельность и конкрентность/concurrency.md
      - Конкурентные паттерны: computer-science/Конкурентные паттерны в Go/concurrency-patterns.md
      - Компьютерные сети: computer-science/Компьютерные сети/computer-networks.md
      - Компьютерные системы: computer-science/Компьютерные системы/computer-systems.md
  - Архитектура и дизайн:
      - Обзор: architecture/index.md
      - Принципы программирования: architecture/Принципы программирования/programming-principles.md
      - ООП в Go: architecture/ООП/oop.md
      - Чистая архитектура: architecture/Чистая архитектура/clean-architecture.md
      - Микросервисная архитектура: architecture/Микросервисная архитектура/microservices.md
      - gRPC: architecture/gRPC/index.md
  - Детали языка:
      - Обзор: go-details/index.md
      - Типы данных: go-details/Типы данных в Go/types.md
      - Массивы и срезы: go-details/Массивы и срезы в Go/arrays-and-slices.md
      - Мапы: go-details/Мапы в Go/maps.md
      - Строки: go-details/Строки в Go/strings.md
      - Интерфейсы: go-details/Интерфейсы в Go/interfaces.md
      - Каналы: go-details/Каналы в Go/channels.md
      - Defer: go-details/Defer в Go/defer.md
      - Замыкания: go-details/Замыкания в Go/closures.md
      - Ошибки: go-details/Ошибки в Go/errors.md
      - Контекст: go-details/Контекст в Go/context.md
      - Дженерики: go-details/Дженерики в Go/generics.md
  - Устройство Go:
      - Обзор: go-fundamentals/index.md
      - Планировщик Go: go-fundamentals/Планировщик Go/scheduler.md
      - Память в Go: go-fundamentals/Память в Go/memory.md
      - Escape Analysis: go-fundamentals/Escape Analysis в Go/escape-analysis.md
      - Сборщик мусора: go-fundamentals/Сбощик мусора в Go/garbage-collector.md
      - Инлайн: go-fundamentals/Инлайн в Go/inlining.md
      - Выравнивание: go-fundamentals/Выравнивание в Go/alignment.md
